# Generated by Django 5.2.6 on 2025-09-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
    ]
